site_name: SZU 课程资料共享
site_description: 深圳大学计算机科学（腾班）本科课程资料共享
repo_url: https://github.com/sakur7a/SZU_Course_Materials/
repo_name: sakur7a/SZU_Course_Materials
theme:
  name: material
  language: zh
  palette:
  - scheme: default
    primary: indigo
    accent: indigo
    toggle:
      icon: material/brightness-7
      name: 切换到深色模式
  - scheme: slate
    primary: indigo
    accent: indigo
    toggle:
      icon: material/brightness-4
      name: 切换到浅色模式
  font:
    text: Noto Sans SC
    code: Fira Code
  features:
  - navigation.instant
  - navigation.tabs
  - navigation.top
  - search.highlight
  - search.suggest
  - toc.follow
plugins:
- search
markdown_extensions:
- toc:
    permalink: true
- admonition
- pymdownx.details
- pymdownx.superfences
extra:
  social:
  - icon: fontawesome/brands/github
    link: https://github.com/sakur7a/SZU_Course_Materials
nav:
- 首页: index.md
- 专业课:
  - 专业英语: c01_3845dfd0.md
  - 人工智能导论: c02_255b42dc.md
  - 数据结构: c03_275d18ed.md
  - 最优化方法: c04_16a83d65.md
  - 计算机系统（1）: c05_60ab8af0.md
- 通识课:
  - 大学物理: c06_a888c48c.md
  - 大学物理实验（1）: c07_efe4ee05.md
  - 概率论与数理统计: c08_53746aff.md
  - 线性代数: c09_aea4562f.md
  - 高等数学: c10_a54321da.md
- 模版与表格: c11_fe36f509.md
- 转专业:
  - 往年原题: c12_e48e732b.md
  - 经验: c13_69719cb4.md
- 贡献指南: contributing.md
- 友情链接: links.md
- 更新日志: changelog.md
