site_name: SZU 课程资料共享
site_description: 深圳大学计算机科学（腾班）本科课程资料共享
repo_url: https://github.com/sakur7a/SZU_Course_Materials/
repo_name: sakur7a/SZU_Course_Materials
theme:
  name: material
  language: zh
  palette:
  - scheme: default
    primary: indigo
    accent: indigo
    toggle:
      icon: material/brightness-7
      name: 切换到深色模式
  - scheme: slate
    primary: indigo
    accent: indigo
    toggle:
      icon: material/brightness-4
      name: 切换到浅色模式
  font:
    text: Noto Sans SC
    code: Fira Code
  features:
  - navigation.instant
  - navigation.tabs
  - navigation.top
  - search.highlight
  - search.suggest
  - toc.follow
plugins:
- search
markdown_extensions:
- toc:
    permalink: true
- admonition
- pymdownx.details
- pymdownx.superfences
extra:
  social:
  - icon: fontawesome/brands/github
    link: https://github.com/sakur7a/SZU_Course_Materials
nav:
- 首页: index.md
- 专业课:
  - 专业英语: professional-english.md
  - 人工智能导论: intro-to-ai.md
  - 数据结构: data-structures.md
  - 最优化方法: optimization-methods.md
  - 计算机系统（1）: computer-systems-1.md
- 通识课:
  - 大学物理: college-physics.md
  - 大学物理实验（1）: college-physics-lab-1.md
  - 概率论与数理统计: probability-and-statistics.md
  - 线性代数: linear-algebra.md
  - 高等数学: advanced-mathematics.md
- 模版与表格: templates-and-forms.md
- 转专业:
  - 往年原题: transfer-past-exams.md
  - 经验: transfer-experience.md
- 贡献指南: contributing.md
- 友情链接: links.md
- 更新日志: changelog.md
